version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:  # Corrected spelling of 'environment'
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "kevoh"
      WORDPRESS_DB_NAME: wordpress
    networks:
      wordpr:
        ipv4_address: "192.168.1.20"

  mysql:
    image: "mysql:5.7"
    environment:  # Corrected spelling of 'environment'
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "kevoh"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      wordpr:
        ipv4_address: "192.168.1.21"

networks:
  wordpr:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
